server.port=8081
spring.application.name=demo
spring.datasource.url=jdbc:mysql://127.0.0.1:6666/booking_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# 2. JPA / HIBERNATE CONFIGURATION
# ===============================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# ===============================
# 3. PAYPAL CONFIGURATION
# ===============================
paypal.client.id=AcC6DSdotHiLMsmHGpWpBbcud8rnrU-nDMAWQDJ3vKvkmLtR0djc499Bjug4JfDXnJsueYkkGXEl2tMg
paypal.client.secret=EE6V38vjJWM-mH0JVljWg3lWnGdLwAK-7PHCzucII4mx0cQploxV7LEsO-O7G63WD22gh9vPotHkRjCA
paypal.mode=sandbox

# ===============================
# 4. PAYOS CONFIGURATION
# ===============================
payos.client.id=2232b460-d19f-4504-aa6a-4489ac060d70
payos.api.key=498f32b7-d028-44b4-9d30-acdea68c64e0
payos.checksum.key=1c6678ec84c27f75bbd88b2129f4e852d33dc56cb569a3c874e053a2b7ad78ab


