server.port=8081
spring.application.name=demo
spring.datasource.url=${DB_URL:jdbc:mysql://mysql-1ec96134-booking-8f94.d.aivencloud.com:20635/defaultdb?useSSL=true&requireSSL=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8}
spring.datasource.username=${DB_USERNAME:avnadmin}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# 2. JPA / HIBERNATE CONFIGURATION
# ===============================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.sql.init.mode=never
spring.sql.init.encoding=UTF-8
spring.jpa.defer-datasource-initialization=true

# ===============================
# 3. PAYPAL CONFIGURATION
# ===============================
paypal.client.id=AXVieCk_PGEgQ1Hbb-VI17HpMiBTUPBgKEfflX5cmMLqdZsNs4L4cTu58kKpke1mcJmFJeNhyV3RX1Pc
paypal.client.secret=EAqhpkFKdrVB4s1fju2sSWsBye4BUJJDp5pGKs95NaxJZxzGJYcYjKW4ZjaxPAQqLAnpMu8_CSytpSRe
paypal.mode=live

# ===============================
# 4. PAYOS CONFIGURATION
# ===============================
payos.client.id=2232b460-d19f-4504-aa6a-4489ac060d70
payos.api.key=498f32b7-d028-44b4-9d30-acdea68c64e0
payos.checksum.key=1c6678ec84c27f75bbd88b2129f4e852d33dc56cb569a3c874e053a2b7ad78ab

# ===============================
# 5. EMAIL CONFIGURATION (Gmail SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=danghainguyen212@gmail.com
spring.mail.password=mtqiwuoteakpdsaa
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true



